### PR TITLE
Dockerize repo

### PR DESCRIPTION
**Pull request by hex337**
* Adds a Dockerfile
* Adds a docker compose file
* Update react-script
* Update README

### CODE REVIEW

**Comment by netmindz** [comment]
Does the auto discovery of the PixelBlaze work?

**Comment by hex337** [comment]
Working through that bit now, this is the error I get:

```
firestorm  | Error: connect ECONNREFUSED 172.26.0.1:81
firestorm  |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16)
firestorm  |     at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
firestorm  |   errno: -111,
firestorm  |   code: 'ECONNREFUSED',
firestorm  |   syscall: 'connect',
firestorm  |   address: '172.26.0.1',
firestorm  |   port: 81
firestorm  | }
firestorm  | ws not alive 172.26.0.1
firestorm  | stopping 172.26.0.1
```

Going to try using host networking on the container.

**Comment by hex337** [comment]
Ok, I think this will only work in linux right now, since the host networking mode is only supported there. Bummer.

**Comment by netmindz** [comment]
I've not used firestorm yet, so don't know if the auto discovery is a convenient or critical aspect

**Comment by netmindz** [comment]
> Working through that bit now, this is the error I get:
> 
> ```
> firestorm  | Error: connect ECONNREFUSED 172.26.0.1:81
> firestorm  |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16)
> firestorm  |     at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
> firestorm  |   errno: -111,
> firestorm  |   code: 'ECONNREFUSED',
> firestorm  |   syscall: 'connect',
> firestorm  |   address: '172.26.0.1',
> firestorm  |   port: 81
> firestorm  | }
> firestorm  | ws not alive 172.26.0.1
> firestorm  | stopping 172.26.0.1
> ```
> 
> Going to try using host networking on the container.

That is talking about port 81, where as I see no reference to that in your config, might need to expose port 81 too

**Comment by hex337** [comment]
Played with the host networking option, but it's only supported in linux for now, so closing this until that changes.

**Pull request closed without merging**
